site_name: litePlay.js
site_url: https://g-ubimus.github.io/litePlay.docs/
theme:
  name: material
  palette:

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: pt
          name: Português
          build: true

nav:
  - Home: index.md
  - play(): play.md
  - eventList class: eventList.md
  - instrument(): instruments.md
